// Контракт аутентификации — пакет auth.v1 сервиса auth (backend/auth).
//
// Владелец: сервис auth (принцип I конституции — сервис владеет своей бизнес-областью
// и данными). cabby-gateway — единственный потребитель в v1 и не имеет доступа к хранилищу
// сервиса.
//
// Канонический файл: backend/contracts/proto/auth/v1/auth.proto (модуль contracts — общий
// для всех микросервисов). Эталонная копия: specs/003-cabber-auth/contracts/auth.proto.
// Копии обязаны совпадать байт-в-байт; равенство проверяет
// TestCanonicalProtoMatchesRepositoryReference.
//
// Версионирование: пакет auth.v1. Новые поля и методы — аддитивно (minor),
// переименование, удаление и изменение семантики существующих полей — несовместимо (major).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterCabberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Отображаемое имя каббера. 1..64 символа (R-08).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Email в форме, полученной от клиента; канонизацию (trim, нижний регистр) выполняет
	// сервис (FR-003). Проверка формата минимальна: ровно один '@' и непустые части (FR-006).
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Пароль в открытом виде только в этом запросе: 4..16 символов (FR-006, R-08).
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCabberRequest) Reset() {
	*x = RegisterCabberRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCabberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCabberRequest) ProtoMessage() {}

func (x *RegisterCabberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCabberRequest.ProtoReflect.Descriptor instead.
func (*RegisterCabberRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterCabberRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterCabberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterCabberRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterCabberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор, назначенный системой и неизменяемый (FR-002). Не является учётными
	// данными (FR-003) и не принимается ни в одном запросе.
	CabberId string `protobuf:"bytes,1,opt,name=cabber_id,json=cabberId,proto3" json:"cabber_id,omitempty"`
	// Канонизированный email созданной учётной записи.
	Email         string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCabberResponse) Reset() {
	*x = RegisterCabberResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCabberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCabberResponse) ProtoMessage() {}

func (x *RegisterCabberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCabberResponse.ProtoReflect.Descriptor instead.
func (*RegisterCabberResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterCabberResponse) GetCabberId() string {
	if x != nil {
		return x.CabberId
	}
	return ""
}

func (x *RegisterCabberResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateCabberSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCabberSessionRequest) Reset() {
	*x = CreateCabberSessionRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCabberSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCabberSessionRequest) ProtoMessage() {}

func (x *CreateCabberSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCabberSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateCabberSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCabberSessionRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCabberSessionRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateCabberSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Непрозрачные данные доступа для заголовка Authorization: Bearer (R-04).
	// В хранилище попадает только их SHA-256 хеш.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Абсолютный предел жизни доступа, Unix-секунды: момент создания + 96 часов (FR-013, R-10).
	// Клиент обязан считать доступ недействительным не позже этого момента; доступ
	// прекращается и раньше — после 24 часов бездействия.
	ExpiresAtUnix int64 `protobuf:"varint,2,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCabberSessionResponse) Reset() {
	*x = CreateCabberSessionResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCabberSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCabberSessionResponse) ProtoMessage() {}

func (x *CreateCabberSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCabberSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateCabberSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCabberSessionResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CreateCabberSessionResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type DeleteCabberSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Тот же токен, что предъявляется в Authorization. Передаётся в теле, а не в metadata,
	// чтобы место, где секрет появляется на стороне сервиса, было единственным.
	AccessToken   string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCabberSessionRequest) Reset() {
	*x = DeleteCabberSessionRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCabberSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCabberSessionRequest) ProtoMessage() {}

func (x *DeleteCabberSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCabberSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCabberSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCabberSessionRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type DeleteCabberSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCabberSessionResponse) Reset() {
	*x = DeleteCabberSessionResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCabberSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCabberSessionResponse) ProtoMessage() {}

func (x *DeleteCabberSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCabberSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteCabberSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

// Уточнение отказа валидации. Перечисляется в google.golang.org/grpc/status.Details().
// При нескольких недостатках возвращается первый в фиксированном порядке
// name -> email -> password (edge case спецификации 003).
type ErrorField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя поля запроса: "name" | "email" | "password".
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Стабильный машинный признак: "empty" | "too_long" | "invalid_format" | "too_short".
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorField) Reset() {
	*x = ErrorField{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorField) ProtoMessage() {}

func (x *ErrorField) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorField.ProtoReflect.Descriptor instead.
func (*ErrorField) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ErrorField) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\"]\n" +
	"\x15RegisterCabberRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"K\n" +
	"\x16RegisterCabberResponse\x12\x1b\n" +
	"\tcabber_id\x18\x01 \x01(\tR\bcabberId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"N\n" +
	"\x1aCreateCabberSessionRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"h\n" +
	"\x1bCreateCabberSessionResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12&\n" +
	"\x0fexpires_at_unix\x18\x02 \x01(\x03R\rexpiresAtUnix\"?\n" +
	"\x1aDeleteCabberSessionRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x1d\n" +
	"\x1bDeleteCabberSessionResponse\":\n" +
	"\n" +
	"ErrorField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xa4\x02\n" +
	"\vAuthService\x12Q\n" +
	"\x0eRegisterCabber\x12\x1e.auth.v1.RegisterCabberRequest\x1a\x1f.auth.v1.RegisterCabberResponse\x12`\n" +
	"\x13CreateCabberSession\x12#.auth.v1.CreateCabberSessionRequest\x1a$.auth.v1.CreateCabberSessionResponse\x12`\n" +
	"\x13DeleteCabberSession\x12#.auth.v1.DeleteCabberSessionRequest\x1a$.auth.v1.DeleteCabberSessionResponseB:Z8github.com/Keane81/Cabby/backend/contracts/authpb;authpbb\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_v1_auth_proto_goTypes = []any{
	(*RegisterCabberRequest)(nil),       // 0: auth.v1.RegisterCabberRequest
	(*RegisterCabberResponse)(nil),      // 1: auth.v1.RegisterCabberResponse
	(*CreateCabberSessionRequest)(nil),  // 2: auth.v1.CreateCabberSessionRequest
	(*CreateCabberSessionResponse)(nil), // 3: auth.v1.CreateCabberSessionResponse
	(*DeleteCabberSessionRequest)(nil),  // 4: auth.v1.DeleteCabberSessionRequest
	(*DeleteCabberSessionResponse)(nil), // 5: auth.v1.DeleteCabberSessionResponse
	(*ErrorField)(nil),                  // 6: auth.v1.ErrorField
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.RegisterCabber:input_type -> auth.v1.RegisterCabberRequest
	2, // 1: auth.v1.AuthService.CreateCabberSession:input_type -> auth.v1.CreateCabberSessionRequest
	4, // 2: auth.v1.AuthService.DeleteCabberSession:input_type -> auth.v1.DeleteCabberSessionRequest
	1, // 3: auth.v1.AuthService.RegisterCabber:output_type -> auth.v1.RegisterCabberResponse
	3, // 4: auth.v1.AuthService.CreateCabberSession:output_type -> auth.v1.CreateCabberSessionResponse
	5, // 5: auth.v1.AuthService.DeleteCabberSession:output_type -> auth.v1.DeleteCabberSessionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
