// Контракт аутентификации — пакет auth.v1 сервиса auth (backend/auth).
//
// Владелец: сервис auth (принцип I конституции — сервис владеет своей бизнес-областью
// и данными). cabby-gateway — единственный потребитель в v1 и не имеет доступа к хранилищу
// сервиса.
//
// Канонический файл: backend/contracts/proto/auth/v1/auth.proto (модуль contracts — общий
// для всех микросервисов). Эталонная копия: specs/003-cabber-auth/contracts/auth.proto.
// Копии обязаны совпадать байт-в-байт; равенство проверяет
// TestCanonicalProtoMatchesRepositoryReference.
//
// Версионирование: пакет auth.v1. Новые поля и методы — аддитивно (minor),
// переименование, удаление и изменение семантики существующих полей — несовместимо (major).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: auth/v1/auth.proto

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_RegisterCabber_FullMethodName      = "/auth.v1.AuthService/RegisterCabber"
	AuthService_CreateCabberSession_FullMethodName = "/auth.v1.AuthService/CreateCabberSession"
	AuthService_DeleteCabberSession_FullMethodName = "/auth.v1.AuthService/DeleteCabberSession"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService — операции учётной записи и доступа каббера. Пакет назван auth.v1, а не
// cabber.v1: сервис предназначен для аутентификации разных ролей (пассажир, администратор),
// но в v1 методов для них нет и объём требований остаётся кабберским.
// Смена и восстановление пароля в v1 сознательно отсутствуют: их нет ни в этом контракте,
// ни в публичном REST-контракте (FR-026 спецификации 003).
type AuthServiceClient interface {
	// Регистрация каббера. Создаёт активную учётную запись, доступ не выдаёт (FR-010).
	//
	//	INVALID_ARGUMENT + ErrorField — некорректное значение поля (FR-006)
	//	ALREADY_EXISTS   — email занят (FR-009); атрибуты существующей записи не раскрываются
	//	UNAVAILABLE      — хранилище недоступно; ложного успеха нет
	RegisterCabber(ctx context.Context, in *RegisterCabberRequest, opts ...grpc.CallOption) (*RegisterCabberResponse, error)
	// Вход: проверяет учётные данные и открывает подтверждённый доступ (FR-011).
	//
	//	UNAUTHENTICATED — единый отказ для «email не найден» и «пароль неверен» (FR-012);
	//	                  NOT_FOUND для учётной записи не используется, чтобы отказ нельзя было
	//	                  использовать для перечисления адресов
	//	INVALID_ARGUMENT + ErrorField — отсутствующие учётные данные
	//	UNAVAILABLE — хранилище недоступно
	CreateCabberSession(ctx context.Context, in *CreateCabberSessionRequest, opts ...grpc.CallOption) (*CreateCabberSessionResponse, error)
	// Выход: отзывает доступ, предъявленный в запросе (FR-019).
	//
	//	UNAUTHENTICATED — отсутствующий, отозванный или истёкший токен; повторный отзыв
	//	                  попадает сюда же (FR-021), ложного успеха нет
	//	UNAVAILABLE — хранилище недоступно
	DeleteCabberSession(ctx context.Context, in *DeleteCabberSessionRequest, opts ...grpc.CallOption) (*DeleteCabberSessionResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) RegisterCabber(ctx context.Context, in *RegisterCabberRequest, opts ...grpc.CallOption) (*RegisterCabberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCabberResponse)
	err := c.cc.Invoke(ctx, AuthService_RegisterCabber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateCabberSession(ctx context.Context, in *CreateCabberSessionRequest, opts ...grpc.CallOption) (*CreateCabberSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCabberSessionResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateCabberSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteCabberSession(ctx context.Context, in *DeleteCabberSessionRequest, opts ...grpc.CallOption) (*DeleteCabberSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCabberSessionResponse)
	err := c.cc.Invoke(ctx, AuthService_DeleteCabberSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService — операции учётной записи и доступа каббера. Пакет назван auth.v1, а не
// cabber.v1: сервис предназначен для аутентификации разных ролей (пассажир, администратор),
// но в v1 методов для них нет и объём требований остаётся кабберским.
// Смена и восстановление пароля в v1 сознательно отсутствуют: их нет ни в этом контракте,
// ни в публичном REST-контракте (FR-026 спецификации 003).
type AuthServiceServer interface {
	// Регистрация каббера. Создаёт активную учётную запись, доступ не выдаёт (FR-010).
	//
	//	INVALID_ARGUMENT + ErrorField — некорректное значение поля (FR-006)
	//	ALREADY_EXISTS   — email занят (FR-009); атрибуты существующей записи не раскрываются
	//	UNAVAILABLE      — хранилище недоступно; ложного успеха нет
	RegisterCabber(context.Context, *RegisterCabberRequest) (*RegisterCabberResponse, error)
	// Вход: проверяет учётные данные и открывает подтверждённый доступ (FR-011).
	//
	//	UNAUTHENTICATED — единый отказ для «email не найден» и «пароль неверен» (FR-012);
	//	                  NOT_FOUND для учётной записи не используется, чтобы отказ нельзя было
	//	                  использовать для перечисления адресов
	//	INVALID_ARGUMENT + ErrorField — отсутствующие учётные данные
	//	UNAVAILABLE — хранилище недоступно
	CreateCabberSession(context.Context, *CreateCabberSessionRequest) (*CreateCabberSessionResponse, error)
	// Выход: отзывает доступ, предъявленный в запросе (FR-019).
	//
	//	UNAUTHENTICATED — отсутствующий, отозванный или истёкший токен; повторный отзыв
	//	                  попадает сюда же (FR-021), ложного успеха нет
	//	UNAVAILABLE — хранилище недоступно
	DeleteCabberSession(context.Context, *DeleteCabberSessionRequest) (*DeleteCabberSessionResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) RegisterCabber(context.Context, *RegisterCabberRequest) (*RegisterCabberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCabber not implemented")
}
func (UnimplementedAuthServiceServer) CreateCabberSession(context.Context, *CreateCabberSessionRequest) (*CreateCabberSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCabberSession not implemented")
}
func (UnimplementedAuthServiceServer) DeleteCabberSession(context.Context, *DeleteCabberSessionRequest) (*DeleteCabberSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCabberSession not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_RegisterCabber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCabberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterCabber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RegisterCabber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterCabber(ctx, req.(*RegisterCabberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateCabberSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCabberSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateCabberSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateCabberSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateCabberSession(ctx, req.(*CreateCabberSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteCabberSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCabberSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteCabberSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_DeleteCabberSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteCabberSession(ctx, req.(*DeleteCabberSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCabber",
			Handler:    _AuthService_RegisterCabber_Handler,
		},
		{
			MethodName: "CreateCabberSession",
			Handler:    _AuthService_CreateCabberSession_Handler,
		},
		{
			MethodName: "DeleteCabberSession",
			Handler:    _AuthService_DeleteCabberSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}
