// Контракт записи местоположения — пакет location.v1 сервиса location (backend/location).
//
// Владелец: сервис location (принцип I конституции — сервис владеет своей бизнес-областью
// и данными). cabby-gateway — единственный потребитель в v1 и не имеет доступа к хранилищу
// сервиса.
//
// Канонический файл: backend/contracts/proto/location/v1/location.proto (модуль contracts).
// Эталонная копия: specs/004-cabber-location/contracts/location.proto. Копии обязаны совпадать
// байт-в-байт; равенство проверяет parity-тест модуля contracts.
//
// Версионирование: пакет location.v1. Новые поля и методы — аддитивно (minor),
// переименование, удаление и изменение семантики существующих полей — несовместимо (major).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: location/v1/location.proto

package locationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordCabberLocationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID каббера из подтверждённой сессии. Пустое или не-UUID значение — INTERNAL, а не
	// INVALID_ARGUMENT: оно означает ошибку gateway, а не клиента.
	CabberId string `protobuf:"bytes,1,opt,name=cabber_id,json=cabberId,proto3" json:"cabber_id,omitempty"`
	// Широта в градусах, -90..90 включительно.
	Latitude float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// Долгота в градусах, -180..180 включительно.
	Longitude     float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordCabberLocationRequest) Reset() {
	*x = RecordCabberLocationRequest{}
	mi := &file_location_v1_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordCabberLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCabberLocationRequest) ProtoMessage() {}

func (x *RecordCabberLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCabberLocationRequest.ProtoReflect.Descriptor instead.
func (*RecordCabberLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{0}
}

func (x *RecordCabberLocationRequest) GetCabberId() string {
	if x != nil {
		return x.CabberId
	}
	return ""
}

func (x *RecordCabberLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RecordCabberLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type RecordCabberLocationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Момент приёма, Unix-секунды и наносекундная доля; назначается сервисом.
	ReceivedAtUnix  int64 `protobuf:"varint,1,opt,name=received_at_unix,json=receivedAtUnix,proto3" json:"received_at_unix,omitempty"`
	ReceivedAtNanos int32 `protobuf:"varint,2,opt,name=received_at_nanos,json=receivedAtNanos,proto3" json:"received_at_nanos,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecordCabberLocationResponse) Reset() {
	*x = RecordCabberLocationResponse{}
	mi := &file_location_v1_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordCabberLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCabberLocationResponse) ProtoMessage() {}

func (x *RecordCabberLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCabberLocationResponse.ProtoReflect.Descriptor instead.
func (*RecordCabberLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{1}
}

func (x *RecordCabberLocationResponse) GetReceivedAtUnix() int64 {
	if x != nil {
		return x.ReceivedAtUnix
	}
	return 0
}

func (x *RecordCabberLocationResponse) GetReceivedAtNanos() int32 {
	if x != nil {
		return x.ReceivedAtNanos
	}
	return 0
}

// Уточнение отказа валидации. Перечисляется в google.golang.org/grpc/status.Details().
// При нескольких недостатках возвращается первый в порядке latitude -> longitude.
type ErrorField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя поля запроса: "latitude" | "longitude".
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Стабильный машинный признак: "not_a_number" | "out_of_range".
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorField) Reset() {
	*x = ErrorField{}
	mi := &file_location_v1_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorField) ProtoMessage() {}

func (x *ErrorField) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorField.ProtoReflect.Descriptor instead.
func (*ErrorField) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ErrorField) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_location_v1_location_proto protoreflect.FileDescriptor

const file_location_v1_location_proto_rawDesc = "" +
	"\n" +
	"\x1alocation/v1/location.proto\x12\vlocation.v1\"t\n" +
	"\x1bRecordCabberLocationRequest\x12\x1b\n" +
	"\tcabber_id\x18\x01 \x01(\tR\bcabberId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"t\n" +
	"\x1cRecordCabberLocationResponse\x12(\n" +
	"\x10received_at_unix\x18\x01 \x01(\x03R\x0ereceivedAtUnix\x12*\n" +
	"\x11received_at_nanos\x18\x02 \x01(\x05R\x0freceivedAtNanos\":\n" +
	"\n" +
	"ErrorField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2~\n" +
	"\x0fLocationService\x12k\n" +
	"\x14RecordCabberLocation\x12(.location.v1.RecordCabberLocationRequest\x1a).location.v1.RecordCabberLocationResponseBBZ@github.com/Keane81/Cabby/backend/contracts/locationpb;locationpbb\x06proto3"

var (
	file_location_v1_location_proto_rawDescOnce sync.Once
	file_location_v1_location_proto_rawDescData []byte
)

func file_location_v1_location_proto_rawDescGZIP() []byte {
	file_location_v1_location_proto_rawDescOnce.Do(func() {
		file_location_v1_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_v1_location_proto_rawDesc), len(file_location_v1_location_proto_rawDesc)))
	})
	return file_location_v1_location_proto_rawDescData
}

var file_location_v1_location_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_location_v1_location_proto_goTypes = []any{
	(*RecordCabberLocationRequest)(nil),  // 0: location.v1.RecordCabberLocationRequest
	(*RecordCabberLocationResponse)(nil), // 1: location.v1.RecordCabberLocationResponse
	(*ErrorField)(nil),                   // 2: location.v1.ErrorField
}
var file_location_v1_location_proto_depIdxs = []int32{
	0, // 0: location.v1.LocationService.RecordCabberLocation:input_type -> location.v1.RecordCabberLocationRequest
	1, // 1: location.v1.LocationService.RecordCabberLocation:output_type -> location.v1.RecordCabberLocationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_location_v1_location_proto_init() }
func file_location_v1_location_proto_init() {
	if File_location_v1_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_v1_location_proto_rawDesc), len(file_location_v1_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_v1_location_proto_goTypes,
		DependencyIndexes: file_location_v1_location_proto_depIdxs,
		MessageInfos:      file_location_v1_location_proto_msgTypes,
	}.Build()
	File_location_v1_location_proto = out.File
	file_location_v1_location_proto_goTypes = nil
	file_location_v1_location_proto_depIdxs = nil
}
