// Контракт записи местоположения — пакет location.v1 сервиса location (backend/location).
//
// Владелец: сервис location (принцип I конституции — сервис владеет своей бизнес-областью
// и данными). cabby-gateway — единственный потребитель в v1 и не имеет доступа к хранилищу
// сервиса.
//
// Канонический файл: backend/contracts/proto/location/v1/location.proto (модуль contracts).
// Эталонная копия: specs/004-cabber-location/contracts/location.proto. Копии обязаны совпадать
// байт-в-байт; равенство проверяет parity-тест модуля contracts.
//
// Версионирование: пакет location.v1. Новые поля и методы — аддитивно (minor),
// переименование, удаление и изменение семантики существующих полей — несовместимо (major).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: location/v1/location.proto

package locationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocationService_RecordCabberLocation_FullMethodName = "/location.v1.LocationService/RecordCabberLocation"
)

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LocationService — запись местоположения каббера. Чтения нет: оно появится отдельной
// спецификацией. Метод доверяет cabber_id: сервис недоступен снаружи сети compose, а личность
// подтверждает cabby-gateway через auth.v1.AuthService.VerifyCabberSession.
type LocationServiceClient interface {
	// Добавляет неизменяемую запись местоположения каббера (FR-001, FR-005). Прежние записи не
	// заменяются. Момент приёма назначает сервис (FR-006). Ограничения частоты нет (FR-007).
	//
	//	INVALID_ARGUMENT + ErrorField — координаты некорректны (FR-002, FR-003); ничего не записано (FR-004)
	//	UNAVAILABLE — хранилище недоступно; ложного успеха нет
	RecordCabberLocation(ctx context.Context, in *RecordCabberLocationRequest, opts ...grpc.CallOption) (*RecordCabberLocationResponse, error)
}

type locationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationServiceClient(cc grpc.ClientConnInterface) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) RecordCabberLocation(ctx context.Context, in *RecordCabberLocationRequest, opts ...grpc.CallOption) (*RecordCabberLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordCabberLocationResponse)
	err := c.cc.Invoke(ctx, LocationService_RecordCabberLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServiceServer is the server API for LocationService service.
// All implementations must embed UnimplementedLocationServiceServer
// for forward compatibility.
//
// LocationService — запись местоположения каббера. Чтения нет: оно появится отдельной
// спецификацией. Метод доверяет cabber_id: сервис недоступен снаружи сети compose, а личность
// подтверждает cabby-gateway через auth.v1.AuthService.VerifyCabberSession.
type LocationServiceServer interface {
	// Добавляет неизменяемую запись местоположения каббера (FR-001, FR-005). Прежние записи не
	// заменяются. Момент приёма назначает сервис (FR-006). Ограничения частоты нет (FR-007).
	//
	//	INVALID_ARGUMENT + ErrorField — координаты некорректны (FR-002, FR-003); ничего не записано (FR-004)
	//	UNAVAILABLE — хранилище недоступно; ложного успеха нет
	RecordCabberLocation(context.Context, *RecordCabberLocationRequest) (*RecordCabberLocationResponse, error)
	mustEmbedUnimplementedLocationServiceServer()
}

// UnimplementedLocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocationServiceServer struct{}

func (UnimplementedLocationServiceServer) RecordCabberLocation(context.Context, *RecordCabberLocationRequest) (*RecordCabberLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordCabberLocation not implemented")
}
func (UnimplementedLocationServiceServer) mustEmbedUnimplementedLocationServiceServer() {}
func (UnimplementedLocationServiceServer) testEmbeddedByValue()                         {}

// UnsafeLocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationServiceServer will
// result in compilation errors.
type UnsafeLocationServiceServer interface {
	mustEmbedUnimplementedLocationServiceServer()
}

func RegisterLocationServiceServer(s grpc.ServiceRegistrar, srv LocationServiceServer) {
	// If the following call panics, it indicates UnimplementedLocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocationService_ServiceDesc, srv)
}

func _LocationService_RecordCabberLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordCabberLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).RecordCabberLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_RecordCabberLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).RecordCabberLocation(ctx, req.(*RecordCabberLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationService_ServiceDesc is the grpc.ServiceDesc for LocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "location.v1.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordCabberLocation",
			Handler:    _LocationService_RecordCabberLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "location/v1/location.proto",
}
